name: Build & Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    defaults:
      run:
        working-directory: example

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode .env
        run: echo "${{ secrets.FLUTTER_ENV }}" > .env
        env:
          FLUTTER_ENV: ${{ secrets.FLUTTER_ENV }}

      - name: Build APK (debug)
        run: flutter build apk --dart-define-from-file=.env --debug

      - name: Build AppBundle (unsigned)
        run: flutter build appbundle --debug

      - name: Upload Artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            example/build/app/outputs/flutter-apk/*.apk
            example/build/app/outputs/bundle/*.aab
          allowUpdates: true
          makeLatest: true
          omitBodyDuringUpdate: true
          
