name: Build & Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: example
        
    steps:
      # 1. Checkout  
      - name: Checkout Repository
        uses: actions/checkout@v4

        # 1) Forçar JDK 11 (evita o erro “Unsupported class file major version 61”

      - name: Check java version
        run: java -version
        
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      # 4. Install Dependencies  
      - name: Install Dependencies
        run: flutter pub get

      # 5. Build APK Debug  
      - name: Build APK Debug
        run: flutter build apk --debug

      # 6. Extrair Versão Atual do pubspec.yaml  
      - name: Extract Version
        id: extract_version
        run: |
          # Ex.: “1.0.0+1”
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "ORIG_VERSION=$version" >> $GITHUB_ENV

      # 7. Obter Última Tag do Git  
      - name: Get Latest Git Tag
        id: latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          tag_prefix: 'v'
      # latest_tag.outputs.latest holds, por ex., "1.0.0+1" :contentReference[oaicite:2]{index=2}

      # 8. Bump Patch/Build se necessário  
      - name: Compute Next Version
        id: bump_version
        run: |
          # Se nenhuma tag, usa ORIG_VERSION
          if [ -z "${{ steps.latest_tag.outputs.latest }}" ]; then
            next=${ORIG_VERSION}
          else
            # separa componentes por '.' ou '+' e incrementa o último (build)
            latest=${{ steps.latest_tag.outputs.latest }}
            next=$(echo "$latest" | awk -F'\\+|\\.' '{
              OFS=".";
              n=split($0,a,/\\+/);
              # a[n] é o build ou último patch
              a[n]=a[n]+1;
              print a[1]"."a[2]"."a[3]"+"a[4];
            }')
          fi
          echo "NEXT_VERSION=$next" >> $GITHUB_ENV
          echo "Computed next version: $next"

      # 9. Check Existing Release via actions/github-script  
      

      # 10. Create Release se não existir  
      - name: Create Release
     #   if: steps.check_release.outputs.exists == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.NEXT_VERSION }}
          release_name: Debug v${{ env.NEXT_VERSION }}
          draft: false
          prerelease: true

      # 11. Upload APK  
      - name: Upload APK
        #if: steps.check_release.outputs.exists == 'false'
       #   working-directory: example
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: example/build/app/outputs/flutter-apk/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
